// lib/products.ts
export interface Product {
  id: number;
  name: string;
  brand: string;
  price: number;
  originalPrice: number;
  discount: number;
  rating: number;
  reviews: number;
  image: string;
  images: string[];
  category: string;
  subcategory: string;
  eventTags: string[];
  sizes: string[];
  colors: string[];
  description: string;
  features: string[];
  inStock: boolean;
}

export const products: Product[] = [
  // -------- MEN --------
  {
    id: 1,
    name: "Classic Cotton Shirt",
    brand: "Aurea",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.2,
    reviews: 1250,
    image: "/classic-cotton-shirt-men-formal-casual-blue-white.jpg",
    images: [
      "/classic-cotton-shirt-men-formal-casual-blue-white.jpg",
      "/men-formal-shirt-blue-cotton-office-wear.jpg",
      "/men-casual-shirt-white-cotton-weekend-wear.jpg",
    ],
    category: "men",
    subcategory: "topwear",
    eventTags: ["men-formal"],
    sizes: ["S", "M", "L", "XL", "XXL"],
    colors: ["Blue", "White", "Light Blue"],
    description:
      "Premium cotton shirt perfect for both formal and casual occasions. Made with 100% cotton fabric for maximum comfort.",
    features: [
      "100% Cotton",
      "Machine Washable",
      "Wrinkle Resistant",
      "Comfortable Fit",
    ],
    inStock: true,
  },
  {
    id: 2,
    name: "Casual Polo T-Shirt",
    brand: "UrbanWear",
    price: 799,
    originalPrice: 1199,
    discount: 33,
    rating: 4.1,
    reviews: 620,
    image: "/men-casual-polo-tshirt.png",
    images: [
      "/men-casual-polo-tshirt.jpg",
      "/men-polo-red.jpg",
      "/men-polo-black.jpg",
    ],
    category: "men",
    subcategory: "topwear",
    eventTags: ["men-casual"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Red", "Navy"],
    description:
      "Soft cotton polo t-shirt with a classic fit. Perfect for casual and semi-formal occasions.",
    features: ["Cotton Blend", "Collared Neck", "Breathable"],
    inStock: true,
  },
  {
    id: 3,
    name: "Linen Kurta",
    brand: "EthnicEdge",
    price: 1599,
    originalPrice: 2299,
    discount: 30,
    rating: 4.5,
    reviews: 980,
    image: "/men-linen-kurta.png",
    images: ["/men-linen-kurta.png", "/men-kurta-white.png"],
    category: "men",
    subcategory: "topwear",
    eventTags: ["men-ethnic"],
    sizes: ["M", "L", "XL"],
    colors: ["Beige", "White"],
    description:
      "Traditional linen kurta ideal for festive and semi-formal occasions. Lightweight and breathable.",
    features: ["Pure Linen", "Hand Wash Recommended", "Straight Cut"],
    inStock: true,
  },
  {
    id: 4,
    name: "Oversized Hoodie",
    brand: "StreetVibe",
    price: 1899,
    originalPrice: 2799,
    discount: 32,
    rating: 4.6,
    reviews: 450,
    image: "/men-oversized-hoodie.png",
    images: ["/men-oversized-hoodie.png", "/men-hoodie-black.png"],
    category: "men",
    subcategory: "topwear",
    eventTags: ["men-casual"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey"],
    description:
      "Casual oversized hoodie with a soft fleece interior. Perfect for winters and streetwear looks.",
    features: ["Fleece Material", "Front Pocket", "Relaxed Fit"],
    inStock: true,
  },
  {
    id: 5,
    name: "Graphic T-Shirt",
    brand: "Trendify",
    price: 699,
    originalPrice: 999,
    discount: 30,
    rating: 4.0,
    reviews: 320,
    image: "/men-graphic-tshirt.png",
    images: ["/men-graphic-tshirt.png", "/men-graphic-white.png"],
    category: "men",
    subcategory: "topwear",
    eventTags: ["men-casual"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["White", "Black"],
    description:
      "Trendy graphic tee for a bold streetwear statement. Soft cotton fabric for comfort.",
    features: ["100% Cotton", "Printed Design", "Slim Fit"],
    inStock: true,
  },

  // ===== BOTTOMWEAR (5) =====
  {
    id: 6,
    name: "Slim Fit Jeans",
    brand: "DenimCo",
    price: 1899,
    originalPrice: 2999,
    discount: 37,
    rating: 4.4,
    reviews: 890,
    image: "/men-slim-fit-jeans-dark-blue-denim-casual.png",
    images: [
      "/men-slim-fit-jeans-dark-blue-denim-casual.png",
      "/men-jeans-light-blue-casual-weekend-wear.png",
    ],
    category: "men",
    subcategory: "bottomwear",
    eventTags: ["men-casual"],
    sizes: ["28", "30", "32", "34", "36", "38"],
    colors: ["Dark Blue", "Light Blue", "Black"],
    description:
      "Comfortable slim fit jeans made from premium denim. Perfect for casual outings and everyday wear.",
    features: [
      "Stretch Denim",
      "Fade Resistant",
      "5 Pocket Design",
      "Slim Fit",
    ],
    inStock: true,
  },
  {
    id: 7,
    name: "Men's Sports Joggers",
    brand: "ActivePro",
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    rating: 4.3,
    reviews: 450,
    image: "/men-sports-joggers.png",
    images: ["/men-sports-joggers.png", "/men-joggers-grey.png"],
    category: "men",
    subcategory: "bottomwear",
    eventTags: ["men-sports"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Grey", "Black"],
    description:
      "Lightweight joggers designed for sports and workouts. Comfortable and durable fabric.",
    features: ["Elastic Waist", "Quick Dry", "Slim Fit"],
    inStock: true,
  },
  {
    id: 8,
    name: "Chino Pants",
    brand: "FormalEase",
    price: 1699,
    originalPrice: 2499,
    discount: 32,
    rating: 4.2,
    reviews: 610,
    image: "/men-chino-pants.jpg",
    images: ["/men-chino-pants.png", "/men-chino-beige.jpg"],
    category: "men",
    subcategory: "bottomwear",
    eventTags: ["men-casual"],
    sizes: ["30", "32", "34", "36"],
    colors: ["Beige", "Navy"],
    description:
      "Classic chino pants suitable for both casual and semi-formal looks.",
    features: ["Cotton Blend", "Slim Fit", "Machine Washable"],
    inStock: true,
  },
  {
    id: 9,
    name: "Cargo Pants",
    brand: "UtilityWear",
    price: 1799,
    originalPrice: 2699,
    discount: 33,
    rating: 4.1,
    reviews: 300,
    image: "/men-cargo-pants.png",
    images: ["/men-cargo-pants.png", "/men-cargo-olive.png"],
    category: "men",
    subcategory: "bottomwear",
    eventTags: ["men-casual"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Olive", "Black"],
    description:
      "Functional cargo pants with multiple pockets. Great for outdoor adventures.",
    features: ["Durable Cotton", "Utility Pockets", "Relaxed Fit"],
    inStock: true,
  },
  {
    id: 10,
    name: "Formal Trousers",
    brand: "OfficeLine",
    price: 1999,
    originalPrice: 2899,
    discount: 31,
    rating: 4.5,
    reviews: 420,
    image: "/men-formal-trousers.png",
    images: ["/men-formal-trousers.png", "/men-formal-grey.jpg"],
    category: "men",
    subcategory: "bottomwear",
    eventTags: ["men-formal"],
    sizes: ["30", "32", "34", "36", "38"],
    colors: ["Black", "Grey", "Navy"],
    description:
      "Elegant formal trousers with a slim fit cut. Ideal for office and formal occasions.",
    features: ["Polyester Blend", "Wrinkle Free", "Slim Fit"],
    inStock: true,
  },

  // ===== FOOTWEAR (5) =====
  {
    id: 11,
    name: "Formal Leather Shoes",
    brand: "EliteStep",
    price: 2499,
    originalPrice: 3999,
    discount: 38,
    rating: 4.6,
    reviews: 780,
    image: "/men-formal-leather-shoes.png",
    images: ["/men-formal-leather-shoes.png", "/men-formal-black-shoes.jpg"],
    category: "men",
    subcategory: "footwear",
    eventTags: ["accessories-formal"],
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Brown", "Black"],
    description:
      "Elegant leather shoes designed for formal occasions and office wear.",
    features: ["Genuine Leather", "Slip Resistant Sole", "Premium Finish"],
    inStock: true,
  },
  {
    id: 12,
    name: "Running Sneakers",
    brand: "SportX",
    price: 2999,
    originalPrice: 4499,
    discount: 33,
    rating: 4.7,
    reviews: 960,
    image: "/men-running-sneakers.png",
    images: ["/men-running-sneakers.png", "/men-sports-shoes-blue.jpg"],
    category: "men",
    subcategory: "footwear",
    eventTags: ["accessories-sports"],
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Blue", "Grey"],
    description:
      "Lightweight sneakers engineered for running and training. High cushioning for maximum comfort.",
    features: ["Breathable Mesh", "Shock Absorbing Sole", "Lightweight"],
    inStock: true,
  },
  {
    id: 13,
    name: "Casual Loafers",
    brand: "ComfortWalk",
    price: 1699,
    originalPrice: 2599,
    discount: 35,
    rating: 4.3,
    reviews: 510,
    image: "/men-casual-loafers.png",
    images: ["/men-casual-loafers.png", "/men-loafers-brown.jpg"],
    category: "men",
    subcategory: "footwear",
    eventTags: ["accessories-casual"],
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Tan", "Brown"],
    description:
      "Stylish loafers for casual wear. Designed with comfort and elegance in mind.",
    features: ["Faux Leather", "Slip On Design", "Cushioned Insole"],
    inStock: true,
  },
  {
    id: 14,
    name: "Flip Flops",
    brand: "BeachWear",
    price: 499,
    originalPrice: 899,
    discount: 44,
    rating: 4.0,
    reviews: 210,
    image: "/men-flipflops.png",
    images: ["/men-flipflops.png", "/men-slippers-blue.jpg"],
    category: "men",
    subcategory: "footwear",
    eventTags: ["accessories-casual"],
    sizes: ["6", "7", "8", "9", "10"],
    colors: ["Blue", "Black"],
    description: "Comfortable flip flops ideal for beach and casual home wear.",
    features: ["Rubber Sole", "Water Resistant", "Lightweight"],
    inStock: true,
  },
  {
    id: 15,
    name: "High Top Sneakers",
    brand: "StreetStyle",
    price: 2299,
    originalPrice: 3299,
    discount: 30,
    rating: 4.4,
    reviews: 640,
    image: "/men-high-top-sneakers.png",
    images: ["/men-high-top-sneakers.png", "/men-sneakers-black.jpg"],
    category: "men",
    subcategory: "footwear",
    eventTags: ["accessories-party"],
    sizes: ["7", "8", "9", "10", "11"],
    colors: ["Black", "White"],
    description: "Trendy high-top sneakers perfect for urban street fashion.",
    features: ["Synthetic Upper", "Durable Sole", "Stylish Design"],
    inStock: true,
  },

  // ===== ACCESSORIES (5) =====
  {
    id: 16,
    name: "Leather Wallet",
    brand: "CarryOn",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    rating: 4.5,
    reviews: 1250,
    image: "/men-leather-wallet.png",
    images: ["/men-leather-wallet.png", "/men-wallet-brown.jpg"],
    category: "men",
    subcategory: "accessories",
    eventTags: ["accessories-formal"],
    sizes: ["One Size"],
    colors: ["Brown", "Black"],
    description:
      "Classic leather wallet with multiple compartments. Compact and durable.",
    features: ["Genuine Leather", "RFID Protection", "Slim Design"],
    inStock: true,
  },
  {
    id: 17,
    name: "Wrist Watch",
    brand: "TimeZone",
    price: 3499,
    originalPrice: 5299,
    discount: 34,
    rating: 4.6,
    reviews: 870,
    image: "/men-wrist-watch.png",
    images: ["/men-wrist-watch.png", "/men-watch-black.jpg"],
    category: "men",
    subcategory: "accessories",
    eventTags: ["accessories-formal"],
    sizes: ["Adjustable"],
    colors: ["Black", "Silver"],
    description:
      "Elegant wrist watch with stainless steel strap. Perfect for formal and casual occasions.",
    features: ["Quartz Movement", "Water Resistant", "Stainless Steel Strap"],
    inStock: true,
  },
  {
    id: 18,
    name: "Sunglasses",
    brand: "SunStyle",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.2,
    reviews: 530,
    image: "/men-sunglasses.png",
    images: ["/men-sunglasses.png", "/men-sunglasses-black.jpg"],
    category: "men",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["One Size"],
    colors: ["Black", "Brown"],
    description: "Stylish UV-protected sunglasses with a classic frame.",
    features: ["UV Protection", "Durable Frame", "Lightweight"],
    inStock: true,
  },
  {
    id: 19,
    name: "Backpack",
    brand: "TravelMate",
    price: 2299,
    originalPrice: 3499,
    discount: 34,
    rating: 4.4,
    reviews: 690,
    image: "/men-backpack.png",
    images: ["/men-backpack.png", "/men-bag-grey.jpg"],
    category: "men",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["One Size"],
    colors: ["Grey", "Black"],
    description:
      "Durable backpack with multiple compartments. Great for office, travel, and casual use.",
    features: ["Water Resistant", "Laptop Compartment", "Ergonomic Design"],
    inStock: true,
  },
  {
    id: 20,
    name: "Cap",
    brand: "HeadGear",
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.1,
    reviews: 310,
    image: "/men-cap.png",
    images: ["/men-cap.png", "/men-cap-black.jpg"],
    category: "men",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["Adjustable"],
    colors: ["Blue", "Black"],
    description:
      "Casual baseball cap with adjustable strap. Perfect for sunny days.",
    features: ["Cotton Blend", "Breathable", "Adjustable Fit"],
    inStock: true,
  },

  // -------- WOMEN --------
  {
    id: 21,
    name: "Casual Top",
    brand: "TrendyWear",
    price: 699,
    originalPrice: 1199,
    discount: 42,
    rating: 4.1,
    reviews: 567,
    image: "/women-casual-top-white-cotton-summer-wear.png",
    images: [
      "/women-casual-top-white-cotton-summer-wear.png",
      "/women-top-pink-casual-summer-comfortable.jpg",
    ],
    category: "women",
    subcategory: "western-wear",
    eventTags: ["women-casual"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["White", "Pink", "Black"],
    description:
      "Comfortable casual top perfect for summer days. Made with breathable cotton fabric.",
    features: ["Cotton Blend", "Breathable", "Short Sleeves", "Regular Fit"],
    inStock: true,
  },
  {
    id: 22,
    name: "Women's Skinny Jeans",
    brand: "DenimQueen",
    price: 1599,
    originalPrice: 2499,
    discount: 36,
    rating: 4.4,
    reviews: 730,
    image: "/women-skinny-jeans.png",
    images: ["/women-skinny-jeans.png", "/women-jeans-black.jpg"],
    category: "women",
    subcategory: "western-wear",
    eventTags: ["women-casual"],
    sizes: ["26", "28", "30", "32", "34"],
    colors: ["Black", "Blue"],
    description:
      "Stylish skinny jeans with stretch fabric for a flattering fit.",
    features: ["Stretch Fabric", "5 Pocket Design", "Slim Fit"],
    inStock: true,
  },
  {
    id: 23,
    name: "Maxi Dress",
    brand: "GlamChic",
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    rating: 4.5,
    reviews: 420,
    image: "/women-maxi-dress.png",
    images: ["/women-maxi-dress.png", "/women-maxi-blue.jpg"],
    category: "women",
    subcategory: "western-wear",
    eventTags: ["women-party"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Blue", "Black", "Red"],
    description: "Elegant maxi dress perfect for evening outings and parties.",
    features: ["Flowy Fabric", "Sleeveless Design", "Comfortable Fit"],
    inStock: true,
  },
  {
    id: 24,
    name: "Blazer",
    brand: "PowerStyle",
    price: 2499,
    originalPrice: 3799,
    discount: 34,
    rating: 4.6,
    reviews: 380,
    image: "/women-blazer.png",
    images: ["/women-blazer.png", "/women-blazer-black.jpg"],
    category: "women",
    subcategory: "western-wear",
    eventTags: ["women-formal"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Black", "Grey"],
    description: "Sophisticated blazer suitable for office and formal events.",
    features: ["Polyester Blend", "Slim Fit", "Full Sleeve"],
    inStock: true,
  },
  {
    id: 25,
    name: "Denim Jacket",
    brand: "CoolEdge",
    price: 1899,
    originalPrice: 2899,
    discount: 34,
    rating: 4.3,
    reviews: 510,
    image: "/women-denim-jacket.png",
    images: ["/women-denim-jacket.png", "/women-jacket-blue.jpg"],
    category: "women",
    subcategory: "western-wear",
    eventTags: ["women-party"],
    sizes: ["S", "M", "L"],
    colors: ["Blue", "Black"],
    description: "Trendy denim jacket for casual streetwear fashion.",
    features: ["Denim Fabric", "Button Closure", "Regular Fit"],
    inStock: true,
  },

  // ===== ETHNIC WEAR (5) =====
  {
    id: 26,
    name: "Floral Print Kurta",
    brand: "Ethnic Wear Co",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    rating: 4.5,
    reviews: 890,
    image: "/floral-print-kurta-women-ethnic-wear-colorful-trad.jpg",
    images: [
      "/floral-print-kurta-women-ethnic-wear-colorful-trad.jpg",
      "/women-ethnic-kurta-pink-floral-traditional.jpg",
      "/women-kurta-blue-ethnic-wear-festival.jpg",
    ],
    category: "women",
    subcategory: "ethnic-wear",
    eventTags: ["women-ethnic"],
    sizes: ["XS", "S", "M", "L", "XL"],
    colors: ["Pink", "Blue", "Green"],
    description:
      "Beautiful floral print kurta perfect for festivals and traditional occasions. Made with soft cotton fabric.",
    features: [
      "Cotton Fabric",
      "Floral Print",
      "3/4 Sleeves",
      "Comfortable Fit",
    ],
    inStock: true,
  },
  {
    id: 27,
    name: "Anarkali Dress",
    brand: "EthnoChic",
    price: 2299,
    originalPrice: 3499,
    discount: 34,
    rating: 4.7,
    reviews: 510,
    image: "/women-anarkali-dress.png",
    images: ["/women-anarkali-dress.png", "/women-anarkali-red.jpg"],
    category: "women",
    subcategory: "ethnic-wear",
    eventTags: ["women-ethnic"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Red", "Blue", "Green"],
    description:
      "Graceful Anarkali dress designed for festive occasions with elegant embroidery.",
    features: ["Embroidered", "Full Length", "Comfortable Fit"],
    inStock: true,
  },
  {
    id: 28,
    name: "Saree",
    brand: "TraditionHub",
    price: 3499,
    originalPrice: 4999,
    discount: 30,
    rating: 4.6,
    reviews: 740,
    image: "/women-saree.png",
    images: ["/women-saree.png", "/women-saree-red.jpg"],
    category: "women",
    subcategory: "ethnic-wear",
    eventTags: ["women-ethnic"],
    sizes: ["Free Size"],
    colors: ["Red", "Green", "Blue"],
    description:
      "Elegant saree with intricate border work, suitable for weddings and festive wear.",
    features: ["Silk Blend", "Lightweight", "Traditional Design"],
    inStock: true,
  },
  {
    id: 29,
    name: "Lehenga Choli",
    brand: "RoyalWear",
    price: 4999,
    originalPrice: 6999,
    discount: 29,
    rating: 4.8,
    reviews: 620,
    image: "/women-lehenga.png",
    images: ["/women-lehenga.png", "/women-lehenga-pink.jpg"],
    category: "women",
    subcategory: "ethnic-wear",
    eventTags: ["women-ethnic"],
    sizes: ["S", "M", "L"],
    colors: ["Pink", "Green", "Red"],
    description:
      "Heavy embroidery lehenga choli designed for weddings and grand occasions.",
    features: ["Embroidered", "Dupatta Included", "Premium Finish"],
    inStock: true,
  },
  {
    id: 30,
    name: "Palazzo Set",
    brand: "ComfortEthnic",
    price: 1799,
    originalPrice: 2599,
    discount: 31,
    rating: 4.3,
    reviews: 410,
    image: "/women-palazzo-set.png",
    images: ["/women-palazzo-set.png", "/women-palazzo-pink.jpg"],
    category: "women",
    subcategory: "ethnic-wear",
    eventTags: ["women-ethnic"],
    sizes: ["S", "M", "L", "XL"],
    colors: ["Pink", "Beige"],
    description:
      "Trendy palazzo set with embroidered kurta. Comfortable for daily wear and semi-formal occasions.",
    features: ["Cotton Blend", "Lightweight", "Stylish Design"],
    inStock: true,
  },

  // ===== FOOTWEAR (5) =====
  {
    id: 31,
    name: "Heeled Sandals",
    brand: "GlamSteps",
    price: 1499,
    originalPrice: 2499,
    discount: 40,
    rating: 4.3,
    reviews: 430,
    image: "/women-heeled-sandals.png",
    images: ["/women-heeled-sandals.png", "/women-heels-black.jpg"],
    category: "women",
    subcategory: "footwear",
    eventTags: ["women-party"],
    sizes: ["5", "6", "7", "8"],
    colors: ["Black", "Beige", "Red"],
    description: "Chic heeled sandals for parties and formal wear.",
    features: ["Comfortable Heel", "Durable Sole", "Trendy Design"],
    inStock: true,
  },
  {
    id: 32,
    name: "Ballet Flats",
    brand: "SoftWalk",
    price: 999,
    originalPrice: 1699,
    discount: 41,
    rating: 4.2,
    reviews: 520,
    image: "/women-ballet-flats.png",
    images: ["/women-ballet-flats.png", "/women-flats-pink.jpg"],
    category: "women",
    subcategory: "footwear",
    eventTags: ["women-casual"],
    sizes: ["5", "6", "7", "8"],
    colors: ["Pink", "Black", "Beige"],
    description: "Comfortable ballet flats for daily and office wear.",
    features: ["PU Leather", "Slip On", "Cushioned Sole"],
    inStock: true,
  },
  {
    id: 33,
    name: "Sneakers",
    brand: "ActiveFit",
    price: 1999,
    originalPrice: 2999,
    discount: 33,
    rating: 4.5,
    reviews: 640,
    image: "/women-sneakers.png",
    images: ["/women-sneakers.png", "/women-sneakers-white.jpg"],
    category: "women",
    subcategory: "footwear",
    eventTags: ["women-sports"],
    sizes: ["5", "6", "7", "8", "9"],
    colors: ["White", "Black"],
    description: "Trendy sneakers suitable for casual wear and workouts.",
    features: ["Breathable Mesh", "Rubber Sole", "Stylish Design"],
    inStock: true,
  },
  {
    id: 34,
    name: "Wedges",
    brand: "StyleStep",
    price: 1799,
    originalPrice: 2699,
    discount: 33,
    rating: 4.4,
    reviews: 410,
    image: "/women-wedges.png",
    images: ["/women-wedges.png", "/women-wedges-black.jpg"],
    category: "women",
    subcategory: "footwear",
    eventTags: ["women-party"],
    sizes: ["5", "6", "7", "8"],
    colors: ["Black", "Beige"],
    description: "Stylish wedges for comfortable yet elegant party wear.",
    features: ["Synthetic Material", "Medium Heel", "Comfortable Design"],
    inStock: true,
  },
  {
    id: 35,
    name: "Kolhapuri Sandals",
    brand: "EthnoStep",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.3,
    reviews: 370,
    image: "/women-kolhapuri.png",
    images: ["/women-kolhapuri.png", "/women-kolhapuri-brown.jpg"],
    category: "women",
    subcategory: "footwear",
    eventTags: ["women-ethnic"],
    sizes: ["5", "6", "7", "8"],
    colors: ["Brown", "Tan"],
    description: "Traditional Kolhapuri sandals ideal for ethnic outfits.",
    features: ["Handmade", "Durable Leather", "Comfortable Sole"],
    inStock: true,
  },

  // ===== ACCESSORIES (5) =====
  {
    id: 36,
    name: "Leather Handbag",
    brand: "BagQueen",
    price: 2599,
    originalPrice: 3999,
    discount: 35,
    rating: 4.6,
    reviews: 810,
    image: "/women-handbag.png",
    images: ["/women-handbag.png", "/women-handbag-black.jpg"],
    category: "women",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["One Size"],
    colors: ["Black", "Brown"],
    description: "Stylish leather handbag for daily use.",
    features: ["Premium Leather", "Spacious", "Durable Design"],
    inStock: true,
  },
  {
    id: 37,
    name: "Earrings Set",
    brand: "Sparkle",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    rating: 4.5,
    reviews: 690,
    image: "/women-earrings.png",
    images: ["/women-earrings.png", "/women-earrings-gold.jpg"],
    category: "women",
    subcategory: "accessories",
    eventTags: ["accessories-party"],
    sizes: ["One Size"],
    colors: ["Gold", "Silver"],
    description: "Trendy earrings set for parties and daily wear.",
    features: ["Alloy", "Durable", "Stylish Design"],
    inStock: true,
  },
  {
    id: 38,
    name: "Sunglasses",
    brand: "ShadeStyle",
    price: 1399,
    originalPrice: 2099,
    discount: 33,
    rating: 4.4,
    reviews: 530,
    image: "/women-sunglasses.png",
    images: ["/women-sunglasses.png", "/women-sunglasses-black.jpg"],
    category: "women",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["One Size"],
    colors: ["Black", "Brown"],
    description: "UV-protected sunglasses for a stylish look.",
    features: ["UV Protection", "Durable Frame", "Lightweight"],
    inStock: true,
  },
  {
    id: 39,
    name: "Wrist Watch",
    brand: "Feminora",
    price: 2999,
    originalPrice: 4699,
    discount: 36,
    rating: 4.6,
    reviews: 780,
    image: "/women-wrist-watch.png",
    images: ["/women-wrist-watch.png", "/women-watch-silver.jpg"],
    category: "women",
    subcategory: "accessories",
    eventTags: ["accessories-formal"],
    sizes: ["Adjustable"],
    colors: ["Silver", "Rose Gold"],
    description:
      "Elegant wrist watch with stainless steel strap for formal and casual wear.",
    features: ["Quartz Movement", "Water Resistant", "Premium Finish"],
    inStock: true,
  },
  {
    id: 40,
    name: "Scarf",
    brand: "SoftStyle",
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.2,
    reviews: 410,
    image: "/women-scarf.png",
    images: ["/women-scarf.png", "/women-scarf-red.jpg"],
    category: "women",
    subcategory: "accessories",
    eventTags: ["accessories-casual"],
    sizes: ["One Size"],
    colors: ["Red", "Blue", "Beige"],
    description: "Lightweight scarf perfect for layering and styling.",
    features: ["Soft Fabric", "Breathable", "Trendy Print"],
    inStock: true,
  },

  // -------- KIDS --------
  // Kids Products

  // 👦 Boys (5 products, includes your existing ones)
  {
    id: 41,
    name: "Kids Cartoon T-Shirt",
    brand: "Little Stars",
    price: 399,
    originalPrice: 599,
    discount: 33,
    rating: 4.3,
    reviews: 567,
    image: "/kids-cartoon-t-shirt-colorful-fun-children-wear.jpg",
    images: [
      "/kids-cartoon-t-shirt-colorful-fun-children-wear.jpg",
      "/kids-t-shirt-blue-cartoon-character-fun.jpg",
    ],
    category: "kids",
    subcategory: "boys",
    eventTags: ["kids-ethnic"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Red", "Blue", "Yellow"],
    description:
      "Fun cartoon printed t-shirt for kids. Made with soft cotton fabric that's gentle on skin.",
    features: [
      "100% Cotton",
      "Cartoon Print",
      "Soft Fabric",
      "Machine Washable",
    ],
    inStock: true,
  },
  {
    id: 42,
    name: "Kids Denim Shorts",
    brand: "TinyTrends",
    price: 499,
    originalPrice: 899,
    discount: 44,
    rating: 4.2,
    reviews: 320,
    image: "/kids-denim-shorts.png",
    images: ["/kids-denim-shorts.png", "/kids-shorts-blue.jpg"],
    category: "kids",
    subcategory: "boys",
    eventTags: ["kids-ethnic"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Blue", "Black"],
    description: "Comfortable denim shorts perfect for summer playtime.",
    features: ["Denim Fabric", "Adjustable Waist", "Casual Fit"],
    inStock: true,
  },
  {
    id: 43,
    name: "Kids Hoodie",
    brand: "CozyKids",
    price: 799,
    originalPrice: 1299,
    discount: 38,
    rating: 4.5,
    reviews: 310,
    image: "/kids-hoodie.png",
    images: ["/kids-hoodie.png", "/kids-hoodie-red.jpg"],
    category: "kids",
    subcategory: "boys",
    eventTags: ["kids-ethnic"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Red", "Grey", "Blue"],
    description: "Warm hoodie for kids, soft fabric ideal for winter wear.",
    features: ["Fleece Fabric", "Front Pocket", "Hooded Design"],
    inStock: true,
  },
  {
    id: 44,
    name: "Kids Cargo Pants",
    brand: "AdventureWear",
    price: 699,
    originalPrice: 1199,
    discount: 42,
    rating: 4.1,
    reviews: 260,
    image: "/kids-cargo-pants.png",
    images: ["/kids-cargo-pants.png", "/kids-cargo-green.jpg"],
    category: "kids",
    subcategory: "boys",
    eventTags: ["kids-ethnic"],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Olive Green", "Brown"],
    description: "Trendy cargo pants for adventurous boys. Durable and comfy.",
    features: ["Cotton Fabric", "Multiple Pockets", "Adjustable Waist"],
    inStock: true,
  },
  {
    id: 45,
    name: "Boys Graphic Sweatshirt",
    brand: "Trendykids",
    price: 899,
    originalPrice: 1499,
    discount: 40,
    rating: 4.4,
    reviews: 210,
    image: "/boys-graphic-sweatshirt.png",
    images: ["/boys-graphic-sweatshirt.png", "/boys-sweatshirt-grey.jpg"],
    category: "kids",
    subcategory: "boys",
    eventTags: ["kids-ethnic"],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Grey", "Navy"],
    description:
      "Stylish sweatshirt with cool graphic print for casual outings.",
    features: ["Soft Fleece", "Graphic Print", "Ribbed Hem"],
    inStock: true,
  },

  // 👧 Girls (5 products, includes your existing one)
  {
    id: 46,
    name: "Girls Party Dress",
    brand: "PrincessWear",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.6,
    reviews: 280,
    image: "/kids-girls-party-dress.png",
    images: ["/kids-girls-party-dress.png", "/kids-dress-pink.jpg"],
    category: "kids",
    subcategory: "girls",
    eventTags: ["kids-ethnic"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Pink", "White"],
    description: "Elegant party dress for girls with lace and flare design.",
    features: ["Soft Fabric", "Flared Design", "Comfortable Fit"],
    inStock: true,
  },
  {
    id: 47,
    name: "Girls Denim Jacket",
    brand: "MiniFashion",
    price: 1099,
    originalPrice: 1799,
    discount: 39,
    rating: 4.5,
    reviews: 350,
    image: "/girls-denim-jacket.png",
    images: ["/girls-denim-jacket.png", "/girls-jacket-blue.jpg"],
    category: "kids",
    subcategory: "girls",
    eventTags: ["kids-ethnic"],
    sizes: ["3-4Y", "5-6Y", "7-8Y", "9-10Y"],
    colors: ["Blue", "Light Blue"],
    description:
      "Trendy denim jacket for girls to pair with dresses and jeans.",
    features: ["Denim Fabric", "Button Closure", "Regular Fit"],
    inStock: true,
  },
  {
    id: 48,
    name: "Girls Leggings Pack",
    brand: "ComfortWear",
    price: 699,
    originalPrice: 1199,
    discount: 42,
    rating: 4.2,
    reviews: 290,
    image: "/girls-leggings.png",
    images: ["/girls-leggings.png", "/girls-leggings-pink.jpg"],
    category: "kids",
    subcategory: "girls",
    eventTags: ["kids-ethnic"],
    sizes: ["2-3Y", "4-5Y", "6-7Y", "8-9Y"],
    colors: ["Black", "Pink", "White"],
    description: "Pack of comfortable stretch leggings for everyday wear.",
    features: ["Stretch Fabric", "Elastic Waist", "Soft Touch"],
    inStock: true,
  },
  {
    id: 49,
    name: "Girls Floral Skirt",
    brand: "CuteStyle",
    price: 799,
    originalPrice: 1399,
    discount: 43,
    rating: 4.3,
    reviews: 220,
    image: "/girls-floral-skirt.png",
    images: ["/girls-floral-skirt.png", "/girls-skirt-pink.jpg"],
    category: "kids",
    subcategory: "girls",
    eventTags: ["kids-ethnic"],
    sizes: ["3-4Y", "5-6Y", "7-8Y"],
    colors: ["Pink", "Yellow"],
    description: "Charming floral skirt for casual and party occasions.",
    features: ["Floral Print", "Elastic Waist", "Flowy Design"],
    inStock: true,
  },
  {
    id: 50,
    name: "Girls Winter Coat",
    brand: "WarmyKids",
    price: 1899,
    originalPrice: 2799,
    discount: 32,
    rating: 4.6,
    reviews: 180,
    image: "/girls-winter-coat.png",
    images: ["/girls-winter-coat.png", "/girls-coat-red.jpg"],
    category: "kids",
    subcategory: "girls",
    eventTags: ["kids-ethnic"],
    sizes: ["4-5Y", "6-7Y", "8-9Y", "10-11Y"],
    colors: ["Red", "Beige"],
    description: "Cozy winter coat to keep girls warm in chilly weather.",
    features: ["Wool Blend", "Button Closure", "Inner Lining"],
    inStock: true,
  },

  // 👶 Infants (5 products new)
  {
    id: 51,
    name: "Infant Romper Set",
    brand: "BabyCuddles",
    price: 599,
    originalPrice: 999,
    discount: 40,
    rating: 4.7,
    reviews: 150,
    image: "/infant-romper.png",
    images: ["/infant-romper.png", "/infant-romper-blue.jpg"],
    category: "kids",
    subcategory: "infants",
    eventTags: ["kids-ethnic"],
    sizes: ["0-3M", "3-6M", "6-9M", "9-12M"],
    colors: ["Blue", "Yellow"],
    description: "Soft cotton romper set for newborn babies.",
    features: ["100% Cotton", "Snap Buttons", "Breathable Fabric"],
    inStock: true,
  },
  {
    id: 52,
    name: "Infant Wool Sweater",
    brand: "SnuggleWear",
    price: 699,
    originalPrice: 1199,
    discount: 42,
    rating: 4.8,
    reviews: 190,
    image: "/infant-wool-sweater.jpg",
    images: ["/infant-wool-sweater.jpg", "/infant-sweater-grey.jpg"],
    category: "kids",
    subcategory: "infants",
    eventTags: ["kids-ethnic"],
    sizes: ["0-6M", "6-12M"],
    colors: ["Grey", "Pink"],
    description: "Warm woolen sweater designed for infants’ delicate skin.",
    features: ["Wool Blend", "Soft Knit", "Lightweight"],
    inStock: true,
  },
  {
    id: 53,
    name: "Infant Booties",
    brand: "BabySteps",
    price: 299,
    originalPrice: 499,
    discount: 40,
    rating: 4.6,
    reviews: 250,
    image: "/infant-booties.jpg",
    images: ["/infant-booties.jpg", "/infant-booties-pink.jpg"],
    category: "kids",
    subcategory: "infants",
    eventTags: ["kids-ethnic"],
    sizes: ["0-6M", "6-12M"],
    colors: ["Pink", "Blue", "White"],
    description: "Cute and comfy booties for newborns.",
    features: ["Soft Sole", "Breathable", "Easy to Wear"],
    inStock: true,
  },
  {
    id: 54,
    name: "Infant Bibs Pack",
    brand: "TinyTots",
    price: 399,
    originalPrice: 699,
    discount: 43,
    rating: 4.7,
    reviews: 210,
    image: "/infant-bibs.jpg",
    images: ["/infant-bibs.jpg", "/infant-bibs-colorful.jpg"],
    category: "kids",
    subcategory: "infants",
    eventTags: ["kids-ethnic"],
    sizes: ["Free Size"],
    colors: ["Mixed Colors"],
    description: "Pack of soft cotton bibs to keep infants clean and dry.",
    features: ["Cotton Fabric", "Absorbent", "Machine Washable"],
    inStock: true,
  },
  {
    id: 55,
    name: "Infant Sleeping Bag",
    brand: "NapTime",
    price: 1299,
    originalPrice: 1999,
    discount: 35,
    rating: 4.9,
    reviews: 120,
    image: "/infant-sleeping-bag.jpg",
    images: ["/infant-sleeping-bag.jpg", "/infant-sleeping-bag-blue.jpg"],
    category: "kids",
    subcategory: "infants",
    eventTags: ["kids-ethnic"],
    sizes: ["0-6M", "6-12M"],
    colors: ["Blue", "Pink"],
    description: "Cozy sleeping bag to keep infants safe and warm.",
    features: ["Padded", "Zipper Closure", "Soft Inner Lining"],
    inStock: true,
  },
];

// Utility functions
export function getProductsByCategory(
  category: string,
  subcategory?: string
): Product[] {
  return products.filter((product) => {
    if (subcategory) {
      return (
        product.category === category && product.subcategory === subcategory
      );
    }
    return product.category === category;
  });
}

export function getProductById(id: number): Product | undefined {
  return products.find((product) => product.id === id);
}

export function searchProducts(query: string): Product[] {
  const lowercaseQuery = query.toLowerCase();
  return products.filter(
    (product) =>
      product.name.toLowerCase().includes(lowercaseQuery) ||
      product.brand.toLowerCase().includes(lowercaseQuery) ||
      product.category.toLowerCase().includes(lowercaseQuery)
  );
}
